theme: jekyll-theme-minimal
title: White House Petitions
description: <center><img src="site_images/white_icon.jpg"> <br> <b>Collaborative Project by:</b> Patrick Vacek, Graham Smith, and I.</center>
