theme: jekyll-theme-minimal
title: /project141b
description: <center><img src="site_images/white_icon.jpg"> <br> <b>Collaborative Project by:</b> Patrick Vacek, Graham Smith, and Edie Espejo.</center>
